import React from 'react';
import { RecommendationResult, LanguageCode } from '../types';
import { Sprout, Printer, X, ShieldCheck } from 'lucide-react';
import { getLocalizedCrop } from '../utils/cropLocalization';

interface ReportModalProps {
  recommendation: RecommendationResult;
  onClose: () => void;
  language: LanguageCode;
}

export const ReportModal: React.FC<ReportModalProps> = ({ recommendation, onClose, language }) => {
  const handlePrint = () => {
    window.print();
  };

  const localizedCrop = getLocalizedCrop(recommendation.crop.id, language);

  const formattedDate = new Date(recommendation.timestamp).toLocaleDateString(
    language === 'te' ? 'te-IN' : language === 'hi' ? 'hi-IN' : 'en-IN',
    {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }
  );

  const labels = language === 'te' ? {
    certificateTitle: 'అధికారిక వ్యవసాయ సలహా పత్రం',
    printBtn: 'ముద్రించండి లేదా PDF గా భద్రపరచండి',
    subHeader: 'జాతీయ వ్యవసాయ పంట సిఫార్సు నివేదిక',
    docId: 'పత్రం సంఖ్య',
    modeSoil: 'మట్టి నమూనా పరీక్ష',
    modeRegion: 'ప్రాంతీయ ప్రామాణికం',
    analysisMode: 'విశ్లేషణ విధానం',
    location: 'ప్రాంతం మరియు రాష్ట్రం',
    fieldSample: 'క్షేత్ర నమూనా విశ్లేషణ',
    soilPh: 'నేల పిహెచ్',
    nutrientBaseline: 'నేల పోషకాల నిష్పత్తి',
    estimatedNote: 'గమనిక: ల్యాబ్ నమూనా లేనందున ప్రాంతీయ ప్రామాణిక గణాంకాలు ఉపయోగించబడ్డాయి.',
    primaryCrop: 'ప్రధాన సిఫార్సు పంట',
    suitability: 'అనుకూలత స్కోరు',
    justificationTitle: 'వ్యవసాయ సమర్థన:',
    nutrientSectionTitle: 'నేల పోషకాల విశ్లేషణ: నేలలో ఉన్నవి vs పంటకు కావలసినవి',
    nutrientHeader: 'పోషకం',
    soilHasHeader: 'నేలలో ఉన్నది',
    cropNeedsHeader: 'పంటకు అవసరం',
    statusHeader: 'పరిస్థితి',
    fertilizerActionHeader: 'సిఫార్సు చేసిన ఎరువు',
    cultivationAdviceTitle: 'ఆచరణాత్మక వ్యవసాయ సాగు సలహాలు',
    disclaimer: 'క్రాప్ యాప్ వ్యవసాయ వ్యవస్థ ద్వారా రూపొందించబడింది. భారతీయ వ్యవసాయ పరిశోధనా మండలి (ICAR) ప్రమాణాలకు అనుగుణంగా తయారుచేయబడింది.',
    signOff: 'క్రాప్ యాప్ కిసాన్ సలహా కేంద్రం',
    certifiedModel: 'ధృవీకరించబడిన వ్యవసాయ నమూనా'
  } : language === 'hi' ? {
    certificateTitle: 'आधिकारिक कृषि परामर्श प्रमाण-पत्र',
    printBtn: 'प्रिंट करें अथवा PDF सुरक्षित करें',
    subHeader: 'राष्ट्रीय कृषि फसल अनुशंसा रिपोर्ट',
    docId: 'दस्तावेज़ संख्या',
    modeSoil: 'मृदा प्रयोगशाला परीक्षण',
    modeRegion: 'क्षेत्रीय मानक',
    analysisMode: 'विश्लेषण का तरीका',
    location: 'स्थान अथवा राज्य',
    fieldSample: 'खेत मृदा विश्लेषण',
    soilPh: 'मृदा पीएच',
    nutrientBaseline: 'पोषक तत्व आधार',
    estimatedNote: 'नोट: लैब रिपोर्ट उपलब्ध न होने के कारण क्षेत्रीय मानक स्तर लागू किए गए हैं।',
    primaryCrop: 'प्रमुख अनुशंसित फसल',
    suitability: 'अनुकूलता स्तर',
    justificationTitle: 'कृषि वैज्ञानिक औचित्य:',
    nutrientSectionTitle: 'मृदा पोषक तत्व विश्लेषण: मिट्टी में क्या है और फसल को क्या चाहिए',
    nutrientHeader: 'पोषक तत्व',
    soilHasHeader: 'मिट्टी में उपलब्ध',
    cropNeedsHeader: 'फसल की आवश्यकता',
    statusHeader: 'स्थिति',
    fertilizerActionHeader: 'अनुशंसित उर्वरक व उपाय',
    cultivationAdviceTitle: 'व्यावहारिक कृषि परामर्श',
    disclaimer: 'क्रॉप ऐप कृषि प्रणाली द्वारा जनरेट किया गया। भारतीय कृषि अनुसंधान परिषद (ICAR) के मानकों के अनुरूप।',
    signOff: 'क्रॉप ऐप किसान परामर्श केंद्र',
    certifiedModel: 'प्रमाणित कृषि वैज्ञानिक मॉडल'
  } : {
    certificateTitle: 'Official Farm Advisory Certificate',
    printBtn: 'Print or Save as PDF',
    subHeader: 'National Agricultural Recommendation Report',
    docId: 'Document ID',
    modeSoil: 'Soil Lab Test',
    modeRegion: 'Regional Benchmark',
    analysisMode: 'Analysis Mode',
    location: 'Location or State',
    fieldSample: 'Field Sample Analysis',
    soilPh: 'Soil pH',
    nutrientBaseline: 'Nutrient Baseline',
    estimatedNote: 'Note: Estimated regional benchmark figures applied because field sample was not specified.',
    primaryCrop: 'Primary Recommended Crop',
    suitability: 'Suitability Score',
    justificationTitle: 'Agronomic Justification:',
    nutrientSectionTitle: 'Soil Nutrient Balance: What Soil Has vs What Crop Needs',
    nutrientHeader: 'Nutrient',
    soilHasHeader: 'Soil Has',
    cropNeedsHeader: 'Crop Requires',
    statusHeader: 'Status',
    fertilizerActionHeader: 'Recommended Fertilizer Action',
    cultivationAdviceTitle: 'Actionable Farmer Cultivation Advice',
    disclaimer: 'Generated by CropApp Agriculture Engine. Complies with Indian Council of Agricultural Research (ICAR) regional crop suitability norms.',
    signOff: 'CropApp Bharat Advisory',
    certifiedModel: 'Validated Agronomic Model'
  };

  const crop = recommendation.crop;
  const soil = recommendation.soilValues;

  const nutrientRows = [
    {
      name: language === 'te' ? 'నత్రజని (Nitrogen)' : language === 'hi' ? 'नाइट्रोजन (N)' : 'Nitrogen (N)',
      soilVal: `${soil.nitrogen} mg/kg`,
      cropVal: `${crop.optimalN} mg/kg (${crop.minN} - ${crop.maxN})`,
      status: soil.nitrogen < crop.minN
        ? (language === 'te' ? 'లోపం' : language === 'hi' ? 'कमी' : 'Deficient')
        : soil.nitrogen > crop.maxN
        ? (language === 'te' ? 'అధికం' : language === 'hi' ? 'अधिकता' : 'Excess')
        : (language === 'te' ? 'సమతుల్యం' : language === 'hi' ? 'संतुलित' : 'Optimal'),
      action: recommendation.fertilizerOptions.find(f => f.nutrient.toLowerCase().includes('nitro') || f.nutrient.toLowerCase().includes('నత్ర') || f.nutrient.toLowerCase().includes('नाइट्रो'))?.fertilizer ||
        (soil.nitrogen < crop.minN ? (language === 'te' ? 'యూరియా లేదా వేపపూత యూరియా వేయండి' : language === 'hi' ? 'नीम लेपित यूरिया का प्रयोग करें' : 'Apply Neem-coated Urea') : (language === 'te' ? 'యూరియా అవసరం లేదు' : language === 'hi' ? 'यूरिया न डालें' : 'No urea needed'))
    },
    {
      name: language === 'te' ? 'భాస్వరం (Phosphorus)' : language === 'hi' ? 'फास्फोरस (P)' : 'Phosphorus (P)',
      soilVal: `${soil.phosphorus} mg/kg`,
      cropVal: `${crop.optimalP} mg/kg (${crop.minP} - ${crop.maxP})`,
      status: soil.phosphorus < crop.minP
        ? (language === 'te' ? 'లోపం' : language === 'hi' ? 'कमी' : 'Deficient')
        : soil.phosphorus > crop.maxP
        ? (language === 'te' ? 'అధికం' : language === 'hi' ? 'अधिकता' : 'Excess')
        : (language === 'te' ? 'సమతుల్యం' : language === 'hi' ? 'संतुलित' : 'Optimal'),
      action: recommendation.fertilizerOptions.find(f => f.nutrient.toLowerCase().includes('phos') || f.nutrient.toLowerCase().includes('భాస్వ') || f.nutrient.toLowerCase().includes('फास्फो'))?.fertilizer ||
        (soil.phosphorus < crop.minP ? (language === 'te' ? 'డిఎపి లేదా సింగిల్ సూపర్ ఫాస్ఫేట్ వేయండి' : language === 'hi' ? 'डीएपी अथवा एसएसपी डालें' : 'Apply DAP or Single Super Phosphate') : (language === 'te' ? 'భాస్వరం అవసరం లేదు' : language === 'hi' ? 'फास्फोरस न डालें' : 'No supplemental phosphate needed'))
    },
    {
      name: language === 'te' ? 'పొటాషియం (Potassium)' : language === 'hi' ? 'पोटाश (K)' : 'Potassium (K)',
      soilVal: `${soil.potassium} mg/kg`,
      cropVal: `${crop.optimalK} mg/kg (${crop.minK} - ${crop.maxK})`,
      status: soil.potassium < crop.minK
        ? (language === 'te' ? 'లోపం' : language === 'hi' ? 'कमी' : 'Deficient')
        : soil.potassium > crop.maxK
        ? (language === 'te' ? 'అధికం' : language === 'hi' ? 'अधिकता' : 'Excess')
        : (language === 'te' ? 'సమతుల్యం' : language === 'hi' ? 'संतुलित' : 'Optimal'),
      action: recommendation.fertilizerOptions.find(f => f.nutrient.toLowerCase().includes('potas') || f.nutrient.toLowerCase().includes('పొటా') || f.nutrient.toLowerCase().includes('पोटा'))?.fertilizer ||
        (soil.potassium < crop.minK ? (language === 'te' ? 'మ్యూరియేట్ ఆఫ్ పొటాష్ (MOP) వాడండి' : language === 'hi' ? 'म्यूरिएट ऑफ पोटाश (MOP) डालें' : 'Apply Muriate of Potash (MOP)') : (language === 'te' ? 'పొటాష్ తగినంత ఉంది' : language === 'hi' ? 'पोटाश पर्याप्त है' : 'Potash is sufficient'))
    },
    {
      name: language === 'te' ? 'నేల పిహెచ్ (pH)' : language === 'hi' ? 'पीएच मान (pH)' : 'Soil pH',
      soilVal: `${soil.ph}`,
      cropVal: `${crop.optimalPh} (${crop.minPh} - ${crop.maxPh})`,
      status: soil.ph < crop.minPh
        ? (language === 'te' ? 'ఆమ్లం' : language === 'hi' ? 'अम्लीय' : 'Acidic')
        : soil.ph > crop.maxPh
        ? (language === 'te' ? 'క్షారం' : language === 'hi' ? 'क्षारीय' : 'Alkaline')
        : (language === 'te' ? 'అనుకూలం' : language === 'hi' ? 'आदर्श' : 'Optimal'),
      action: soil.ph < crop.minPh
        ? (language === 'te' ? 'నేలలో సున్నం లేదా డోలమైట్ కలపండి' : language === 'hi' ? 'खेत में चूना अथवा डोलोमाइट मिलाएं' : 'Incorporate agricultural lime')
        : soil.ph > crop.maxPh
        ? (language === 'te' ? 'నేలలో జిప్సం లేదా సేంద్రియ ఎరువు వేయండి' : language === 'hi' ? 'जिप्सम या हरी खाद का प्रयोग करें' : 'Apply gypsum or green manure')
        : (language === 'te' ? 'పిహెచ్ మార్పు అవసరం లేదు' : language === 'hi' ? 'पीएच स्तर पूरी तरह संतुलित है' : 'pH is perfectly balanced')
    }
  ];

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto print:p-0 print:bg-white print:static">
      <div className="bg-white rounded-2xl max-w-3xl w-full p-8 shadow-2xl relative max-h-[92vh] overflow-y-auto border border-neutral-200 print:max-h-none print:shadow-none print:border-none print:p-0">
        {/* Header (Screen only actions) */}
        <div className="flex items-center justify-between pb-6 border-b border-neutral-200 print:hidden">
          <div className="flex items-center gap-2 text-emerald-800 font-bold text-sm">
            <ShieldCheck className="w-5 h-5 text-emerald-600" />
            <span>{labels.certificateTitle}</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-emerald-700 hover:bg-emerald-800 text-white text-xs font-bold shadow transition-colors"
            >
              <Printer className="w-4 h-4" />
              <span>{labels.printBtn}</span>
            </button>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-full bg-neutral-100 hover:bg-neutral-200 text-neutral-700 flex items-center justify-center text-sm font-bold"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Document Body */}
        <div className="mt-6 space-y-6 text-neutral-900 font-sans">
          {/* Official Letterhead */}
          <div className="flex items-start justify-between border-b-2 border-emerald-800 pb-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-lg bg-emerald-800 text-white flex items-center justify-center">
                <Sprout className="w-7 h-7 text-emerald-300" />
              </div>
              <div>
                <h1 className="text-2xl font-black tracking-tight text-emerald-950 font-serif">
                  CROPAPP
                </h1>
                <p className="text-xs font-bold text-emerald-700 tracking-wider uppercase">
                  {labels.subHeader}
                </p>
              </div>
            </div>

            <div className="text-right text-xs text-neutral-500">
              <p className="font-mono font-bold text-neutral-800">{labels.docId}: {recommendation.id}</p>
              <p className="mt-0.5">{formattedDate}</p>
              <span className="inline-block mt-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-emerald-100 text-emerald-800">
                {recommendation.mode === 'soil' ? labels.modeSoil : labels.modeRegion}
              </span>
            </div>
          </div>

          {/* Farm Location & Input Baseline */}
          <div className="bg-neutral-50 p-4 rounded-xl border border-neutral-200 text-xs">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              <div>
                <span className="text-neutral-500 block">{labels.analysisMode}:</span>
                <strong className="text-neutral-900 text-xs">
                  {recommendation.mode === 'soil' ? labels.modeSoil : labels.modeRegion}
                </strong>
              </div>
              <div>
                <span className="text-neutral-500 block">{labels.location}:</span>
                <strong className="text-neutral-900 text-xs">
                  {recommendation.regionDetails?.district
                    ? `${recommendation.regionDetails.district}, ${recommendation.regionDetails.state}`
                    : labels.fieldSample}
                </strong>
              </div>
              <div>
                <span className="text-neutral-500 block">{labels.soilPh}:</span>
                <strong className="text-neutral-900 text-xs tabular-nums">
                  {recommendation.soilValues.ph} ({recommendation.soilHealth.phStatus})
                </strong>
              </div>
              <div>
                <span className="text-neutral-500 block">{labels.nutrientBaseline}:</span>
                <strong className="text-neutral-900 text-xs tabular-nums">
                  N: {recommendation.soilValues.nitrogen} | P: {recommendation.soilValues.phosphorus} | K: {recommendation.soilValues.potassium}
                </strong>
              </div>
            </div>
            {recommendation.soilValues.isEstimated && (
              <p className="mt-2 text-[11px] text-amber-900 italic border-t border-neutral-200 pt-1.5">
                {labels.estimatedNote}
              </p>
            )}
          </div>

          {/* Recommended Crop Hero */}
          <div className="border-2 border-emerald-600/60 p-5 rounded-xl bg-emerald-50/40">
            <div className="flex items-start justify-between">
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-emerald-800">
                  {labels.primaryCrop}
                </span>
                <h2 className="text-3xl font-black text-emerald-950 font-serif mt-1">
                  {localizedCrop.name}
                </h2>
                <p className="text-xs text-neutral-600 mt-0.5">
                  {localizedCrop.category} • {localizedCrop.season}
                </p>
              </div>

              <div className="text-right">
                <span className="text-xs font-semibold text-neutral-500 block">{labels.suitability}</span>
                <span className="text-3xl font-black text-emerald-800 tabular-nums">
                  {recommendation.matchPercentage}%
                </span>
              </div>
            </div>

            <div className="mt-4 pt-3 border-t border-emerald-200/80 text-xs text-neutral-800">
              <p>
                <strong>{labels.justificationTitle} </strong>
                {localizedCrop.description}
              </p>
            </div>
          </div>

          {/* What Soil Has vs What Crop Needs Table */}
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-neutral-800 mb-2">
              {labels.nutrientSectionTitle}
            </h3>
            <table className="w-full text-left text-xs border border-neutral-200 rounded-lg overflow-hidden">
              <thead className="bg-neutral-100 text-neutral-600">
                <tr>
                  <th className="p-2.5 border-b border-neutral-200">{labels.nutrientHeader}</th>
                  <th className="p-2.5 border-b border-neutral-200">{labels.soilHasHeader}</th>
                  <th className="p-2.5 border-b border-neutral-200">{labels.cropNeedsHeader}</th>
                  <th className="p-2.5 border-b border-neutral-200">{labels.statusHeader}</th>
                  <th className="p-2.5 border-b border-neutral-200">{labels.fertilizerActionHeader}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-neutral-200">
                {nutrientRows.map((row, i) => (
                  <tr key={i} className="hover:bg-neutral-50/50">
                    <td className="p-2.5 font-bold text-neutral-900">{row.name}</td>
                    <td className="p-2.5 font-semibold text-neutral-800 tabular-nums">{row.soilVal}</td>
                    <td className="p-2.5 text-neutral-600 tabular-nums">{row.cropVal}</td>
                    <td className="p-2.5">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        row.status.includes('లోపం') || row.status.includes('कमी') || row.status === 'Deficient' || row.status.includes('ఆమ్లం') || row.status.includes('క్షారం') || row.status.includes('अम्लीय') || row.status.includes('क्षारीय')
                          ? 'bg-amber-100 text-amber-900 border border-amber-300'
                          : row.status.includes('సమతుల్యం') || row.status.includes('संतुलित') || row.status.includes('అనుకూలం') || row.status.includes('आदर्श') || row.status === 'Optimal'
                          ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                          : 'bg-blue-100 text-blue-900 border border-blue-300'
                      }`}>
                        {row.status}
                      </span>
                    </td>
                    <td className="p-2.5 text-neutral-800 font-medium text-[11px]">{row.action}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Actionable Cultivation Advice */}
          <div>
            <h3 className="text-sm font-bold uppercase tracking-wider text-neutral-800 mb-2">
              {labels.cultivationAdviceTitle}
            </h3>
            <ul className="space-y-1.5 text-xs text-neutral-700 bg-neutral-50 p-4 rounded-xl border border-neutral-200">
              {recommendation.farmerAdvice.map((adv, idx) => (
                <li key={idx} className="flex items-start gap-2">
                  <span className="text-emerald-700 font-bold shrink-0">•</span>
                  <span>{adv}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Official Sign-off & Disclaimer */}
          <div className="pt-4 border-t border-neutral-200 flex flex-col sm:flex-row items-start sm:items-center justify-between text-[11px] text-neutral-500 gap-4">
            <p className="max-w-md">
              {labels.disclaimer}
            </p>
            <div className="text-right shrink-0">
              <span className="font-bold text-neutral-800 block">{labels.signOff}</span>
              <span>{labels.certifiedModel}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
